// <auto-generated />
using System;
using Conexus.Api.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conexus.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Conexus.Api.Domain.Models.Aluno", b =>
                {
                    b.Property<int>("Idaluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idaluno"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("complemento");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idusuario");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("responsavel");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rua");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ativo','trancado','cancelado')")
                        .HasColumnName("situacao")
                        .HasDefaultValueSql("'ativo'");

                    b.Property<string>("TelResponsavel")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("tel_responsavel");

                    b.HasKey("Idaluno")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idusuario" }, "idusuario");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.AlunoTurma", b =>
                {
                    b.Property<int>("IdalunoTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno_turma");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdalunoTurma"));

                    b.Property<DateOnly?>("DataMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("data_matricula")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Idaluno")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    b.Property<int>("Idturma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idturma");

                    b.HasKey("IdalunoTurma")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idaluno", "Idturma" }, "idaluno")
                        .IsUnique();

                    b.HasIndex(new[] { "Idturma" }, "idturma");

                    b.ToTable("aluno_turma", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Avaliacao", b =>
                {
                    b.Property<int>("Idavaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idavaliacao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idavaliacao"));

                    b.Property<DateOnly>("DataAvaliacao")
                        .HasColumnType("date")
                        .HasColumnName("data_avaliacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdalunoTurma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno_turma");

                    b.Property<int>("Idfuncionario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idfuncionario");

                    b.Property<int>("Idturma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idturma");

                    b.Property<decimal?>("Nota")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nota");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("Peso")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("peso")
                        .HasDefaultValueSql("'1.00'");

                    b.Property<string>("Titulo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Idavaliacao")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdalunoTurma" }, "idaluno_turma");

                    b.HasIndex(new[] { "Idfuncionario" }, "idfuncionario");

                    b.HasIndex(new[] { "Idturma" }, "idturma")
                        .HasDatabaseName("idturma1");

                    b.ToTable("avaliacao", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.CalendarioAula", b =>
                {
                    b.Property<int>("Idaula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idaula");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idaula"));

                    b.Property<bool?>("AulaExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("aula_extra")
                        .HasDefaultValueSql("'0'");

                    b.Property<DateOnly>("DataAula")
                        .HasColumnType("date")
                        .HasColumnName("data_aula");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("Idfuncionario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idfuncionario");

                    b.Property<int>("Idmaterial")
                        .HasColumnType("int(11)")
                        .HasColumnName("idmaterial");

                    b.Property<int>("Idturma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idturma");

                    b.Property<string>("LinkReuniao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("link_reuniao");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Sala")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sala");

                    b.HasKey("Idaula")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idfuncionario" }, "idfuncionario")
                        .HasDatabaseName("idfuncionario1");

                    b.HasIndex(new[] { "Idmaterial" }, "idmaterial");

                    b.HasIndex(new[] { "Idturma" }, "idturma")
                        .HasDatabaseName("idturma2");

                    b.ToTable("calendario_aula", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Cartao", b =>
                {
                    b.Property<int>("Idcartao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idcartao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idcartao"));

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bandeira");

                    b.Property<int>("Idaluno")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_titular");

                    b.Property<string>("NumeroCriptografado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("numero_criptografado");

                    b.Property<string>("UltimosDigitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("char(4)")
                        .HasColumnName("ultimos_digitos")
                        .IsFixedLength();

                    b.Property<string>("ValidadeAno")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("validade_ano")
                        .IsFixedLength();

                    b.Property<string>("ValidadeMes")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("validade_mes")
                        .IsFixedLength();

                    b.HasKey("Idcartao")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idaluno" }, "idaluno")
                        .HasDatabaseName("idaluno1");

                    b.ToTable("cartao", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Contato", b =>
                {
                    b.Property<int>("Idcontato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idcontato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idcontato"));

                    b.Property<string>("Arquivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("arquivo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idusuario");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mensagem");

                    b.Property<string>("MotivoContato")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo_contato");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.HasKey("Idcontato")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idusuario" }, "idusuario")
                        .HasDatabaseName("idusuario1");

                    b.ToTable("contato", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.DocumentoAluno", b =>
                {
                    b.Property<int>("Iddocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("iddocumento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Iddocumento"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime?>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<int>("Idaluno")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    b.Property<int>("IdtipoDocumento")
                        .HasColumnType("int(11)")
                        .HasColumnName("idtipo_documento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("StatusDocumento")
                        .HasColumnType("enum('pendente','aprovado','invalido')")
                        .HasColumnName("status_documento");

                    b.HasKey("Iddocumento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idaluno" }, "idaluno")
                        .HasDatabaseName("idaluno2");

                    b.HasIndex(new[] { "IdtipoDocumento" }, "idtipo_documento");

                    b.ToTable("documento_aluno", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.EmprestimoMaterial", b =>
                {
                    b.Property<int>("Idemprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idemprestimo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idemprestimo"));

                    b.Property<DateOnly?>("DataDevolvido")
                        .HasColumnType("date")
                        .HasColumnName("data_devolvido");

                    b.Property<DateOnly>("DataEmprestimo")
                        .HasColumnType("date")
                        .HasColumnName("data_emprestimo");

                    b.Property<DateOnly>("DataPrevistaDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista_devolucao");

                    b.Property<int>("Idaluno")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    b.Property<int>("Idmaterial")
                        .HasColumnType("int(11)")
                        .HasColumnName("idmaterial");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('emprestado','devolvido','atrasado')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'emprestado'");

                    b.Property<decimal?>("ValorMulta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_multa")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("Idemprestimo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idaluno" }, "idaluno")
                        .HasDatabaseName("idaluno3");

                    b.HasIndex(new[] { "Idmaterial" }, "idmaterial")
                        .HasDatabaseName("idmaterial1");

                    b.ToTable("emprestimo_material", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.FormaPagamento", b =>
                {
                    b.Property<int>("IdformaPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idforma_pagamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdformaPagamento"));

                    b.Property<string>("FormaPagamento1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("forma_pagamento");

                    b.HasKey("IdformaPagamento")
                        .HasName("PRIMARY");

                    b.ToTable("forma_pagamento", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Funcionario", b =>
                {
                    b.Property<int>("Idfuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idfuncionario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idfuncionario"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("especialidade");

                    b.Property<int>("Idusuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idusuario");

                    b.HasKey("Idfuncionario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idusuario" }, "idusuario")
                        .HasDatabaseName("idusuario2");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Idioma", b =>
                {
                    b.Property<int>("Ididioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ididioma");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Ididioma"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Ididioma")
                        .HasName("PRIMARY");

                    b.ToTable("idioma", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Material", b =>
                {
                    b.Property<int>("Idmaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idmaterial");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idmaterial"));

                    b.Property<string>("Arquivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("arquivo");

                    b.Property<DateTime?>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("current_timestamp()");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("FormatoArquivo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("formato_arquivo");

                    b.Property<int>("Ididioma")
                        .HasColumnType("int(11)")
                        .HasColumnName("ididioma");

                    b.Property<int>("Idnivel")
                        .HasColumnType("int(11)")
                        .HasColumnName("idnivel");

                    b.Property<int>("IdtipoMaterial")
                        .HasColumnType("int(11)")
                        .HasColumnName("idtipo_material");

                    b.Property<int?>("Idturma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idturma");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Idmaterial")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Ididioma" }, "ididioma");

                    b.HasIndex(new[] { "Idnivel" }, "idnivel");

                    b.HasIndex(new[] { "IdtipoMaterial" }, "idtipo_material");

                    b.HasIndex(new[] { "Idturma" }, "idturma")
                        .HasDatabaseName("idturma3");

                    b.ToTable("material", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Nivel", b =>
                {
                    b.Property<int>("Idnivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idnivel");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idnivel"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.HasKey("Idnivel")
                        .HasName("PRIMARY");

                    b.ToTable("nivel", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Pagamento", b =>
                {
                    b.Property<int>("Idpagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idpagamento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idpagamento"));

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("Idaluno")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno");

                    b.Property<int>("IdformaPagamento")
                        .HasColumnType("int(11)")
                        .HasColumnName("idforma_pagamento");

                    b.Property<decimal?>("Multa")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("multa")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("StatusPagamento")
                        .HasColumnType("enum('pendente','pago','atrasado')")
                        .HasColumnName("status_pagamento");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Idpagamento")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idaluno" }, "idaluno")
                        .HasDatabaseName("idaluno4");

                    b.HasIndex(new[] { "IdformaPagamento" }, "idforma_pagamento");

                    b.ToTable("pagamento", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Presenca", b =>
                {
                    b.Property<int>("Idpresenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idpresenca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idpresenca"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("IdalunoTurma")
                        .HasColumnType("int(11)")
                        .HasColumnName("idaluno_turma");

                    b.Property<int>("Idfuncionario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idfuncionario");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("presente");

                    b.HasKey("Idpresenca")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdalunoTurma" }, "idaluno_turma")
                        .HasDatabaseName("idaluno_turma1");

                    b.HasIndex(new[] { "Idfuncionario" }, "idfuncionario")
                        .HasDatabaseName("idfuncionario2");

                    b.ToTable("presenca", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdtipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idtipo_documento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdtipoDocumento"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.HasKey("IdtipoDocumento")
                        .HasName("PRIMARY");

                    b.ToTable("tipo_documento", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.TipoMaterial", b =>
                {
                    b.Property<int>("IdtipoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idtipo_material");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdtipoMaterial"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao");

                    b.HasKey("IdtipoMaterial")
                        .HasName("PRIMARY");

                    b.ToTable("tipo_material", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Turma", b =>
                {
                    b.Property<int>("Idturma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idturma");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idturma"));

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("int(11)")
                        .HasColumnName("capacidade_maxima");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("DiasSemana")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dias_semana");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("Idfuncionario")
                        .HasColumnType("int(11)")
                        .HasColumnName("idfuncionario");

                    b.Property<int>("Ididioma")
                        .HasColumnType("int(11)")
                        .HasColumnName("ididioma");

                    b.Property<int>("Idnivel")
                        .HasColumnType("int(11)")
                        .HasColumnName("idnivel");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagem");

                    b.Property<string>("Sala")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sala");

                    b.Property<string>("TipoRecorrencia")
                        .HasColumnType("enum('diaria','semanal','mensal')")
                        .HasColumnName("tipo_recorrencia");

                    b.HasKey("Idturma")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Idfuncionario" }, "idfuncionario")
                        .HasDatabaseName("idfuncionario3");

                    b.HasIndex(new[] { "Ididioma" }, "ididioma")
                        .HasDatabaseName("ididioma1");

                    b.HasIndex(new[] { "Idnivel" }, "idnivel")
                        .HasDatabaseName("idnivel1");

                    b.ToTable("turma", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Idusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idusuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idusuario"));

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo")
                        .HasDefaultValueSql("'1'");

                    b.Property<bool?>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bloqueado")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("papel");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<int?>("TentativasLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("tentativas_login")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Idusuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Aluno", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Alunos")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("aluno_ibfk_1");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.AlunoTurma", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Aluno", "IdalunoNavigation")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("Idaluno")
                        .IsRequired()
                        .HasConstraintName("aluno_turma_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Turma", "IdturmaNavigation")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("Idturma")
                        .IsRequired()
                        .HasConstraintName("aluno_turma_ibfk_2");

                    b.Navigation("IdalunoNavigation");

                    b.Navigation("IdturmaNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Avaliacao", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.AlunoTurma", "IdalunoTurmaNavigation")
                        .WithMany("Avaliacaos")
                        .HasForeignKey("IdalunoTurma")
                        .IsRequired()
                        .HasConstraintName("avaliacao_ibfk_2");

                    b.HasOne("Conexus.Api.Domain.Models.Funcionario", "IdfuncionarioNavigation")
                        .WithMany("Avaliacaos")
                        .HasForeignKey("Idfuncionario")
                        .IsRequired()
                        .HasConstraintName("avaliacao_ibfk_3");

                    b.HasOne("Conexus.Api.Domain.Models.Turma", "IdturmaNavigation")
                        .WithMany("Avaliacaos")
                        .HasForeignKey("Idturma")
                        .IsRequired()
                        .HasConstraintName("avaliacao_ibfk_1");

                    b.Navigation("IdalunoTurmaNavigation");

                    b.Navigation("IdfuncionarioNavigation");

                    b.Navigation("IdturmaNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.CalendarioAula", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Funcionario", "IdfuncionarioNavigation")
                        .WithMany("CalendarioAulas")
                        .HasForeignKey("Idfuncionario")
                        .IsRequired()
                        .HasConstraintName("calendario_aula_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Material", "IdmaterialNavigation")
                        .WithMany("CalendarioAulas")
                        .HasForeignKey("Idmaterial")
                        .IsRequired()
                        .HasConstraintName("calendario_aula_ibfk_3");

                    b.HasOne("Conexus.Api.Domain.Models.Turma", "IdturmaNavigation")
                        .WithMany("CalendarioAulas")
                        .HasForeignKey("Idturma")
                        .IsRequired()
                        .HasConstraintName("calendario_aula_ibfk_2");

                    b.Navigation("IdfuncionarioNavigation");

                    b.Navigation("IdmaterialNavigation");

                    b.Navigation("IdturmaNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Cartao", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Aluno", "IdalunoNavigation")
                        .WithMany("Cartaos")
                        .HasForeignKey("Idaluno")
                        .IsRequired()
                        .HasConstraintName("cartao_ibfk_1");

                    b.Navigation("IdalunoNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Contato", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Contatos")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("contato_ibfk_1");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.DocumentoAluno", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Aluno", "IdalunoNavigation")
                        .WithMany("DocumentoAlunos")
                        .HasForeignKey("Idaluno")
                        .IsRequired()
                        .HasConstraintName("documento_aluno_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.TipoDocumento", "IdtipoDocumentoNavigation")
                        .WithMany("DocumentoAlunos")
                        .HasForeignKey("IdtipoDocumento")
                        .IsRequired()
                        .HasConstraintName("documento_aluno_ibfk_2");

                    b.Navigation("IdalunoNavigation");

                    b.Navigation("IdtipoDocumentoNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.EmprestimoMaterial", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Aluno", "IdalunoNavigation")
                        .WithMany("EmprestimoMaterials")
                        .HasForeignKey("Idaluno")
                        .IsRequired()
                        .HasConstraintName("emprestimo_material_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Material", "IdmaterialNavigation")
                        .WithMany("EmprestimoMaterials")
                        .HasForeignKey("Idmaterial")
                        .IsRequired()
                        .HasConstraintName("emprestimo_material_ibfk_2");

                    b.Navigation("IdalunoNavigation");

                    b.Navigation("IdmaterialNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Funcionario", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Usuario", "IdusuarioNavigation")
                        .WithMany("Funcionarios")
                        .HasForeignKey("Idusuario")
                        .IsRequired()
                        .HasConstraintName("funcionario_ibfk_1");

                    b.Navigation("IdusuarioNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Material", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Idioma", "IdidiomaNavigation")
                        .WithMany("Materials")
                        .HasForeignKey("Ididioma")
                        .IsRequired()
                        .HasConstraintName("material_ibfk_2");

                    b.HasOne("Conexus.Api.Domain.Models.Nivel", "IdnivelNavigation")
                        .WithMany("Materials")
                        .HasForeignKey("Idnivel")
                        .IsRequired()
                        .HasConstraintName("material_ibfk_3");

                    b.HasOne("Conexus.Api.Domain.Models.TipoMaterial", "IdtipoMaterialNavigation")
                        .WithMany("Materials")
                        .HasForeignKey("IdtipoMaterial")
                        .IsRequired()
                        .HasConstraintName("material_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Turma", "IdturmaNavigation")
                        .WithMany("Materials")
                        .HasForeignKey("Idturma")
                        .HasConstraintName("material_ibfk_4");

                    b.Navigation("IdidiomaNavigation");

                    b.Navigation("IdnivelNavigation");

                    b.Navigation("IdtipoMaterialNavigation");

                    b.Navigation("IdturmaNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Pagamento", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Aluno", "IdalunoNavigation")
                        .WithMany("Pagamentos")
                        .HasForeignKey("Idaluno")
                        .IsRequired()
                        .HasConstraintName("pagamento_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.FormaPagamento", "IdformaPagamentoNavigation")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdformaPagamento")
                        .IsRequired()
                        .HasConstraintName("pagamento_ibfk_2");

                    b.Navigation("IdalunoNavigation");

                    b.Navigation("IdformaPagamentoNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Presenca", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.AlunoTurma", "IdalunoTurmaNavigation")
                        .WithMany("Presencas")
                        .HasForeignKey("IdalunoTurma")
                        .IsRequired()
                        .HasConstraintName("presenca_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Funcionario", "IdfuncionarioNavigation")
                        .WithMany("Presencas")
                        .HasForeignKey("Idfuncionario")
                        .IsRequired()
                        .HasConstraintName("presenca_ibfk_2");

                    b.Navigation("IdalunoTurmaNavigation");

                    b.Navigation("IdfuncionarioNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Turma", b =>
                {
                    b.HasOne("Conexus.Api.Domain.Models.Funcionario", "IdfuncionarioNavigation")
                        .WithMany("Turmas")
                        .HasForeignKey("Idfuncionario")
                        .IsRequired()
                        .HasConstraintName("turma_ibfk_1");

                    b.HasOne("Conexus.Api.Domain.Models.Idioma", "IdidiomaNavigation")
                        .WithMany("Turmas")
                        .HasForeignKey("Ididioma")
                        .IsRequired()
                        .HasConstraintName("turma_ibfk_2");

                    b.HasOne("Conexus.Api.Domain.Models.Nivel", "IdnivelNavigation")
                        .WithMany("Turmas")
                        .HasForeignKey("Idnivel")
                        .IsRequired()
                        .HasConstraintName("turma_ibfk_3");

                    b.Navigation("IdfuncionarioNavigation");

                    b.Navigation("IdidiomaNavigation");

                    b.Navigation("IdnivelNavigation");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Aluno", b =>
                {
                    b.Navigation("AlunoTurmas");

                    b.Navigation("Cartaos");

                    b.Navigation("DocumentoAlunos");

                    b.Navigation("EmprestimoMaterials");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.AlunoTurma", b =>
                {
                    b.Navigation("Avaliacaos");

                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.FormaPagamento", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Funcionario", b =>
                {
                    b.Navigation("Avaliacaos");

                    b.Navigation("CalendarioAulas");

                    b.Navigation("Presencas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Idioma", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Material", b =>
                {
                    b.Navigation("CalendarioAulas");

                    b.Navigation("EmprestimoMaterials");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Nivel", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.TipoDocumento", b =>
                {
                    b.Navigation("DocumentoAlunos");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.TipoMaterial", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");

                    b.Navigation("Avaliacaos");

                    b.Navigation("CalendarioAulas");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Conexus.Api.Domain.Models.Usuario", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Contatos");

                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
